### PR TITLE
Add Wezterm colorschema setting

### PR DESCRIPTION
**Pull request by mortymacs**
Hi,

Thanks for your great theme!

Cheers,
Mort

### CODE REVIEW

**Comment by spcbfr** [comment]
I'll test the colorscheme with this term whenever I can and merge if everything looks good

**Comment by pineapplegiant** [comment]
Thanks @spcbfr for looking at this :)

**Comment by mortymacs** [comment]
No news?

**Comment by pineapplegiant** [comment]
Lmao, I'll take a look this weekend. I'm sure it's good.

**Comment by mortymacs** [comment]
> Lmao, I'll take a look this weekend. I'm sure it's good.
> 
> Also how is Wezterm? I'm thinking of trying it out from Alacritty (bc ligatures).

Great, thanks!

Wezterm was a good experience as it renders icons correctly and also supports Lua scripting which lets you add your own custom logic. I was using it for a while, and then I decided to switch back to Alacritty as my font issue was resolved and also he main reason I decided to start using Wezterm was it renders all icons correctly. But, after a while I decided to switched back to Alacritty as my font issue was resolved and also I discovered that Alacritty offers a smoother experience than Wezterm and I'm using it now. Alacritty renders icons as ascii characters while Wezterm renders it as its actual shape. So, it requires more processing for Wezterm. Maybe it the newer version of Wezterm they fixed it, but I didn't try it. I also liked Wezterm as it supports Lua script. So, you can add your own custom functions and so on.

**Comment by spcbfr** [comment]
Been a little busy lately

**Comment by mortymacs** [comment]
> Lmao, I'll take a look this weekend. I'm sure it's good.
> 
> Also how is Wezterm? I'm thinking of trying it out from Alacritty (bc ligatures).

Great, thanks!

Wezterm was a good experience as it renders icons correctly without any size or gap issues, which was what exactly I was looking for. It also supports Lua scripting which lets you add your own custom logic. I was using it for a while, and then I decided to switch back to Alacritty.

**Pull request closed without merging**
